# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_auto_20190322_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
